stages:
  - lint
  - test
  - build

lint:
  tags:
    - runner-beast
  image: node:20
  stage: lint
  before_script:
    - cd frontend; if (-not $?) { exit 1 }
    - npm install  
  script:
    - npm run lint
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'

test:
  tags:
    - runner-beast
  image: node:20
  stage: test
  before_script:
    - cd backend; if (-not $?) { exit 1 }  
    - npm install  
    - npx prisma generate --schema=./db/prisma/schema.prisma
  script:
    - npm run test
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'

build:
  tags:
    - runner-beast
  image: node:20
  stage: build
  before_script:
    - cd frontend; if (-not $?) { exit 1 }  
    - npm install 
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/dist
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'